name: Auto-PR-Check

on:
  pull_request_target:
    types: [ opened ]

jobs:
  check-pr-head:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        if: ${{startsWith(github.event.pull_request.head.ref, 'dev')}}
        with:
          comment: ":no_entry_sign Cancel merge of deployment (dev-*) branch to master or release branch according to branch strategy policy."
